import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const getData = () => {
    const url =
    'https://accounts.zoho.com/oauth/v2/auth?response_type=code&client_id=1000.N048ZP6F4A8B2F7T8BR0FL2RDTVZRG&scope=ZohoProjects.portals.ALL&redirect_uri=http://localhost:3000/SignIn/signIn&prompt=consent'
    
    axios.get(url, {
      headers: {
      'Content-Type': "application/json;charset=utf-8",
      'Access-Control-Allow-Origin': 'http://localhost:3000',
      }  
    })
    .then((res) => console.log('res', res))
    .catch((err) => console.log('err', err))

    //getToken()
  }

  const getToken = () => {
    axios.post('https://accounts.zoho.com/oauth/v2/token?client_id=1000.N048ZP6F4A8B2F7T8BR0FL2RDTVZRG&grant_type=authorization_code&client_secret=442f37ba77a2a42b719d9aad641ba3d81b978b9d54&redirect_uri=http://localhost:3000/SignIn/signIn&code=1000.161c71ea2e9246507597f95451bc8331.e794382aef768e56396eebbda3a07fe1')
    .then((result) => console.log("result", result))
    .catch((err) => console.log(err))
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <button onClick={getData}>Sign In with Facebook</button>

          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
